# Set prefix to Ctrl-Space
unbind C-b

set -g prefix C-Space
bind C-Space send-prefix

# Send the *current* pane to a chosen window (prompts for target)
bind M-p command-prompt -p "create pane from:" "join-pane -s ':%%'"

# Send pane into new window
bind P break-pane

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# new window (tab)
bind t new-window

# next/previous window  ALT-t
bind -n M-t next-window

# switch panes using Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# reload config file
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

