# Set prefix to Ctrl-Space
unbind C-b

set -g prefix C-Space
bind C-Space send-prefix

# Send the *current* pane to a chosen window (prompts for target)
bind M-p command-prompt -p "create pane from:"  "join-pane -s ':%%'"

# Send pane into new window
bind P break-pane

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# new window (tab)
bind -n M-t new-window

set-option -g default-shell /usr/bin/zsh

# next/previous window  ALT-t
bind -n M-T next-window

# switch to window by number (Alt-0 .. Alt-9)
bind -n M-0 select-window -t :0
bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9

# switch panes using Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# reload config file
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# scrollback in nvim 
bind-key E run-shell '
  tmpfile="$(mktemp /tmp/tmux-scrollback-XXXXXX.log)" &&
  tmux capture-pane -pS -32768 > "$tmpfile" &&
  tmux new-window "nvim \"$tmpfile\""
  '

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off


# Start window and pane numbering at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
setw -g pane-base-index 1

# (Optional) Keep numbering compact after closing a window
set -g renumber-windows on

# status bar
set -g status-bg "#CAC5E3"
set -g status-position bottom

# powerline
# source /usr/share/powerline/bindings/tmux/powerline.conf
